trigger: none

pr: none

pool: Stratsys-buildagents

variables:
- group: "Azure Key Vault"
- name: buildConfiguration
  value: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: 'src\HtmlSanitizer\HtmlSanitizer.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Package
  inputs:
    command: 'pack'
    packagesToPack: 'src\HtmlSanitizer\HtmlSanitizer.csproj'
    versioningScheme: off

- script: dotnet nuget push $(Build.ArtifactStagingDirectory)\**\*.nupkg --api-key $(GH-PACKAGES-TOKEN-WRITE) --source "https://nuget.pkg.github.com/stratsys/index.json"
  displayName: Push
